# Generated by Django 5.0.1 on 2024-08-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='genero',
            field=models.CharField(default='sin genero', max_length=10),
        ),
    ]
