# Generated by Django 5.0.1 on 2024-09-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_docente_id_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='direccion',
        ),
    ]
