# Generated by Django 5.0.1 on 2024-09-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_sede_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='direccion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
