# Generated by Django 5.0.1 on 2024-09-15 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_sede_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='direccion',
        ),
    ]
