# Generated by Django 5.0.1 on 2024-09-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_sede_direccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SedeUsuario',
        ),
    ]
