# Generated by Django 5.0.1 on 2024-09-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_cinturon_dan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinturon',
            name='color_cinturon',
            field=models.CharField(max_length=50),
        ),
    ]
