# Generated by Django 5.0.1 on 2024-10-01 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(max_length=30)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('grupo', models.CharField(max_length=50)),
                ('id_docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.docente')),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sede')),
            ],
            options={
                'db_table': 'Horario',
            },
        ),
    ]
