# Generated by Django 5.0.1 on 2024-10-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_horario_frecuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='aforo',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='frecuencia',
            field=models.CharField(default=10, max_length=30),
            preserve_default=False,
        ),
    ]
