# Generated by Django 5.0.1 on 2024-10-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_horario_aforo_horario_frecuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='periodo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
