# Generated by Django 5.0.1 on 2024-10-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_clase_gratis'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase_gratis',
            name='estado',
            field=models.CharField(default='En espera', max_length=20),
        ),
    ]
