# Generated by Django 5.0.1 on 2024-11-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alumno'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alumno',
            table='Alumno',
        ),
    ]
