# Generated by Django 5.0.1 on 2024-11-05 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_alumno_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('estado', models.CharField(default='sin pagar', max_length=20)),
                ('qr_yape', models.ImageField(blank=True, default='/imagenes_bd/qr_yape/qr_default.jpeg', null=True, upload_to='qr_yape/')),
                ('comprobante_pago', models.ImageField(blank=True, null=True, upload_to='imagenes_bd/')),
                ('fecha', models.DateField()),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alumno')),
                ('id_horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.horario')),
            ],
        ),
    ]
