# Generated by Django 5.0.1 on 2024-11-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='qr_yape',
        ),
    ]
