# Generated by Django 5.0.1 on 2024-08-17 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_docente_id_sede_alter_docente_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='id_sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sede'),
        ),
    ]
