# Generated by Django 5.0.1 on 2024-08-23 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_sedeusuario_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='id_sede',
        ),
    ]
