# Generated by Django 5.0.1 on 2024-09-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_sede_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
    ]
