# Generated by Django 5.0.1 on 2024-09-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_sede_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='direccion',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
