# Generated by Django 5.0.1 on 2024-09-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_sedeusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinturon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_cinturon', models.CharField(max_length=30)),
                ('kup', models.IntegerField()),
                ('dan', models.ImageField(upload_to='')),
            ],
        ),
    ]
