# Generated by Django 5.0.1 on 2024-09-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cinturon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinturon',
            name='color_cinturon',
            field=models.CharField(max_length=15),
        ),
    ]
