# Generated by Django 5.0.1 on 2024-09-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_cinturon_color_cinturon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinturon',
            name='dan',
            field=models.IntegerField(),
        ),
    ]
