# Generated by Django 5.0.1 on 2024-10-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_horario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
