# Generated by Django 5.0.1 on 2024-10-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='frecuencia',
        ),
    ]
