# Generated by Django 5.0.1 on 2024-10-28 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_horario_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase_Gratis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.IntegerField()),
                ('id_horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.horario')),
            ],
            options={
                'db_table': 'Clase_Gratis',
            },
        ),
    ]
