# Generated by Django 5.0.1 on 2024-11-18 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_matricula_qr_yape'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('id_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.horario')),
            ],
            options={
                'db_table': 'Asistencia',
            },
        ),
        migrations.CreateModel(
            name='Asistencia_alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=10)),
                ('id_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asistencia')),
            ],
            options={
                'db_table': 'Asistencia_alumno',
            },
        ),
    ]
