# Generated by Django 5.0.1 on 2024-11-18 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_asistencia_asistencia_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia_alumno',
            name='id_alumno',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='app.alumno'),
            preserve_default=False,
        ),
    ]
