# Generated by Django 5.0.1 on 2024-11-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_asistencia_alumno_id_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='telefono',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
