# Generated by Django 5.0.1 on 2024-11-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_docente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='telefono',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
