# Generated by Django 5.0.1 on 2024-11-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alumno_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='foto_local',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_bd/'),
        ),
    ]
